### ISSUE TITLE
升级遇到bug，更新表结构失败

### ISSUE THREAD

**Issue by qdxkrs** [infra-fe/rap-client#12]
**BUG描述**
打不开网页

**复现步骤**
升级镜像后执行
docker exec my_rap_server node scripts/updateSchema

**期望结果**
升级成功

**实际结果**
升级失败

**截图**
![图片](https://user-images.githubusercontent.com/39894542/205809501-cda821de-0ed0-4135-8685-6ed9b0dc713e.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息
docker镜像版本
**附加信息**

**Comment by ashleyshar** [comment]
已有的数据库，建议执行server端database下新增sql文件，v2021~v2022前缀的都是后续的改动

**Comment by ashleyshar** [comment]
最新镜像已修复
