### ISSUE TITLE
自动完成功能

### ISSUE THREAD

**Issue by Bosn** [infra-fe/rap-client#2]
RAP1的功能，RAP2一直没做，就是可以通过 变量名 + 快捷键，快速复制一段结构（包括带嵌套的复杂结构）

这个功能很好用，但是同名问题比较麻烦，之前是先改一个临时名，这里可以做一下优化，比如让用户选择接口。

**Comment by ashleyshar** [comment]
https://infra-fe.github.io/rap-client/guide/interface/basic#shortcuts
